### ISSUE TITLE
the VM Deployment are not deployed but machines was created in the v center when connectiong more than one vm deployment to a vlan when deploying using setup script

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#298]
STR
Have an environment with a auto vlan  and setup script
Add three VM Deployment apps to the environment 
connect the three VM Deployment to the vlan 
reserve the environment 

BIR
the VM Deployment are not deployed but machines was created in the v center

**Comment by tornizanQ** [comment]
Cannot reproduce as it described. But still it isn't working, now the setup fails with the following error in the activity feed:

rror: General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
09/Mar/2016 08:25:51 INFO Deploying apps for reservation <cloudshell.api.cloudshell_api.GetReservationDescriptionResponseInfo instance at 0x022FC5A8>. App names: VM Deployment, VM Deployment1, VM Deployment2
Traceback (most recent call last):
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tor.n\AppData\Local\Temp\db564e6b-3e36-426f-a8e7-e0a75fd49af8\Default Sandbox Setup.zip\__main__.py", line 8, in <module>
  File "C:\Users\tor.n\AppData\Local\Temp\db564e6b-3e36-426f-a8e7-e0a75fd49af8\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\tor.n\AppData\Local\Temp\db564e6b-3e36-426f-a8e7-e0a75fd49af8\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 19, in execute
  File "C:\Users\tor.n\AppData\Local\Temp\db564e6b-3e36-426f-a8e7-e0a75fd49af8\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 42, in _deploy_apps_in_reservation
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 2215, in ExecuteDeployAppCommandBulk
    return self.generateAPIRequest(OrderedDict([('method_name', 'ExecuteDeployAppCommandBulk'), ('reservationId', reservationId), ('appNames', appNames), ('commandInputs', CommonAPIRequest.toContainer(commandInputs)), ('printOutput', printOutput)]))
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 332, in generateAPIRequest
    response_str = self._sendRequest(self.username, self.domain, method_name, request_str)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 1520, in _sendRequest
    return CommonAPISession._sendRequest(self, operation, message, request_headers)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 279, in _sendRequest
    response = urllib23.urlopen(request_object)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

Parameters:




Server Logs
[Logs.zip](https://github.com/QualiSystems/vCenterShell/files/164623/Logs.zip)

**Comment by tornizanQ** [comment]
Reproduced on 17/3/16 10:35 
Server and Ex logs:
[ExLogs.zip](https://github.com/QualiSystems/vCenterShell/files/177500/ExLogs.zip)
[ServerLogs.zip](https://github.com/QualiSystems/vCenterShell/files/177501/ServerLogs.zip)


![image](https://cloud.githubusercontent.com/assets/17527106/13840782/5b67a280-ec2d-11e5-9fa9-b6cd42471271.png)


Could be related to this bug
https://github.com/QualiSystems/vCenterShell/issues/309

**Comment by doppleware** [comment]
This was very helpful! Thanks.
Looks like this is a server issue

**Comment by doppleware** [comment]
Should be fixed by:
http://team:8080/tfs/Quali-Collection/QualiSystems/_versionControl/changeset/150915

Get latest on server.

**Comment by TomerAdmon** [comment]
still doesn't work: 

![image](https://cloud.githubusercontent.com/assets/12639815/13914067/c1368e08-ef54-11e5-943f-66a51de51161.png)

Error: Script runner exited with exit code: 1
Description: Logger File Handler is: C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\core\logger\../../Logs\48ac4c8d-b5a4-4410-a628-9fd006614eb1\Default--21-Mar-2016--11-03-05.log
Error executing Autoload command on deployed app Photon_78464445. Error: There is no driver associated with the resource 'Photon_78464445'100
Error executing Autoload command on deployed app Photon2_2fa84cee. Error: There is no driver associated with the resource 'Photon2_2fa84cee'100
Error executing Autoload command on deployed app Photon1_c1c507b5. Error: There is no driver associated with the resource 'Photon1_c1c507b5'100
Traceback (most recent call last):
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tomer.a\AppData\Local\Temp\218bc7f6-e863-4399-9b74-3b26a889d6e3\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\Users\tomer.a\AppData\Local\Temp\218bc7f6-e863-4399-9b74-3b26a889d6e3\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\tomer.a\AppData\Local\Temp\218bc7f6-e863-4399-9b74-3b26a889d6e3\Default Sandbox Setup.zip\environment_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\Users\tomer.a\AppData\Local\Temp\218bc7f6-e863-4399-9b74-3b26a889d6e3\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 29, in execute
  File "C:\Users\tomer.a\AppData\Local\Temp\218bc7f6-e863-4399-9b74-3b26a889d6e3\Default Sandbox Setup.zip\environment_scripts\env_setup\setup_script.py", line 83, in _connect_all_routes_in_reservation
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 1800, in ConnectRoutesInReservation
    return self.generateAPIRequest(OrderedDict([('method_name', 'ConnectRoutesInReservation'), ('reservationId', reservationId), ('endpoints', CommonAPIRequest.toContainer(endpoints)), ('mappingType', mappingType)]))
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 382, in generateAPIRequest
    raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
cloudshell.api.common_cloudshell_api.CloudShellAPIError: CloudShell API error 100: 'str' object has no attribute 'name'

Parameters:

[TeamServer.Service - Copy.txt](https://github.com/QualiSystems/vCenterShell/files/181862/TeamServer.Service.-.Copy.txt)

[QsRuntimeService - Copy.txt](https://github.com/QualiSystems/vCenterShell/files/181864/QsRuntimeService.-.Copy.txt)

**Comment by doppleware** [comment]
Was a regression, should now be fixed

**Comment by tornizanQ** [comment]
Verified
